### ISSUE TITLE
can you backtest on this model

### ISSUE THREAD

**Issue by sweendoozle** [Omar-Karimov/ChartScanAI#1]
is this possible

**Comment by Omar-Karimov** [comment]
Hi @sweendoozle,

Thank you for your interest in ChartScanAI, and sorry for the late response!

Yes, backtesting is absolutely possible with this model. You can apply it to historical candlestick data, generate Buy/Sell signals using the model, and simulate trades to evaluate performance metrics such as precision, win rate, or financial returns.
